### PR TITLE
support more shader stages

### PR DESCRIPTION
**Pull request by ukari**
vulkan [shader spec](https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap10.html#shaders-vertex)
```
9.5. Vertex Shaders
9.6. Tessellation Control Shaders
9.7. Tessellation Evaluation Shaders
9.8. Geometry Shaders
9.9. Fragment Shaders
9.10. Compute Shaders
9.11. Ray Generation Shaders
9.12. Intersection Shaders
9.13. Any-Hit Shaders
9.14. Closest Hit Shaders
9.15. Miss Shaders
9.16. Callable Shaders
```

vulkan [mesh + task spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_mesh_shader.html)

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks!

Would it be possible for you to manually test a ray tracing shader? When I used these last I had to specify the SPIR-V version: https://github.com/expipiplus1/vulkan/blob/master/examples/rays/Pipeline.hs#L189

**Comment by ukari** [comment]
It seems some comments about `compileShaderQ` is wrong, so I fix it.

I test `rgen.glsl` shader in both `shaderc/glslc` and `glslang/glslangValidator` in shell, it needs `spirv1.4`. So I passed needed flag which could specify spirv1.4 for functions about ray tracing shaders. And now `compileShader` and `compileShaderQ` in `ShaderQQ/Shaderc.hs` have different signatures, I guess there should be a minor version upgrade due to this api changed.

For `task`/`mesh` shaders, I test and found that they could be compile to `spirv1.0`, so no changes made on them.

Here is the [test shaders](https://gist.github.com/ukari/7056c5591a5e2a4663e7fee04cd31ff8). I have few knowledge about hlsl so I use a example from [wihlidal blog](https://www.wihlidal.com/blog/graphics/2019-05-28-vk-rust-ray-tracing-hlsl/), and my test on `rgen.hlsl` returns `rgen.hlsl: rgen.hlsl(12): error at column 31, HLSL parsing failed.`. Consider that the [spec](https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release) says that `Vulkan 1.1 ` and `SPIR-V 1.4` are needed for ray tracing, I didn't test hlsl anymore.

**Comment by ukari** [comment]
I noticed that both `glslang/glslangValidator` and `shaderc/glslc` could compile both `glsl` and `hlsl`.

What is the purpose for [`Utils/ShaderQQ.hs`](https://github.com/expipiplus1/vulkan/blob/af7292074758fd1b130e880cbe73c433efba2b3f/utils/src/Vulkan/Utils/ShaderQQ.hs#L180) and [`Utils/ShaderQQ/Shaderc.hs`](https://github.com/expipiplus1/vulkan/blob/af7292074758fd1b130e880cbe73c433efba2b3f/utils/src/Vulkan/Utils/ShaderQQ/Shaderc.hs#L173) use different `glsl/hlsl` shader to `spirv` compile tool?

Or should there be a refactor like the stuffs below?
```
- Vulkan/Utils/Shader/Common.hs
- Vulkan/Utils/Shader/GLSL/Shaderc.hs
- Vulkan/Utils/Shader/GLSL/Glslang.hs
- Vulkan/Utils/Shader/HLSL/Shaderc.hs
- Vulkan/Utils/Shader/HLSL/Glslang.hs
```

**Comment by expipiplus1** [comment]
Thanks for all this!

> Or should there be a refactor like the stuffs below?
> 
> ```
> - Vulkan/Utils/Shader/Common.hs
> - Vulkan/Utils/Shader/GLSL/Shaderc.hs
> - Vulkan/Utils/Shader/GLSL/Glslang.hs
> - Vulkan/Utils/Shader/HLSL/Shaderc.hs
> - Vulkan/Utils/Shader/HLSL/Glslang.hs
> ```

That sounds like an excellent idea! It is the way it is currently because I wanted an example of using both `shaderc` and `glslc` and an example of using GLSL and HLSL and this was the simplest way to do it :)

Do you intend to do this refactoring? (I'm very happy to merge this in the meantime)

**Comment by ukari** [comment]
#### now the structure
```
exposed-modules:
      Vulkan.Utils.ShaderQQ.Backend.Glslang (GlslangError, GlslangWarning, processGlslangMessages)
      Vulkan.Utils.ShaderQQ.Backend.Shaderc (ShadercError, ShadercWarning, processShadercMessages)
      Vulkan.Utils.ShaderQQ.GLSL.Glslang (glsl, vert .. mesh, compileShaderQ, compileShader)
      Vulkan.Utils.ShaderQQ.GLSL.Shaderc (glsl, vert .. mesh, compileShaderQ, compileShader)
      Vulkan.Utils.ShaderQQ.HLSL.Glslang (hlsl, vert .. mesh, compileShaderQ, compileShader)
      Vulkan.Utils.ShaderQQ.HLSL.Shaderc (hlsl, vert .. mesh, compileShaderQ, compileShader)
  other-modules:
      Vulkan.Utils.ShaderQQ.ShaderType
      Vulkan.Utils.ShaderQQ.Backend.Glslang.Internal
      Vulkan.Utils.ShaderQQ.Backend.Shaderc.Internal
      Vulkan.Utils.ShaderQQ.GLSL
      Vulkan.Utils.ShaderQQ.HLSL
```

#### about `Vulkan.Utils.ShaderQQ.HLSL.Glslang`
when compile a `hlsl` shader, `glslangValidator` needs to pass a entry point name explicitly while `glslc` could auto detect entry point.

`frag.hlsl`
``` hlsl
float4 main([[vk::location(0)]] const float3 col) : SV_TARGET
{
    return float4(col, 1);
}
```

- glslangValidator with entry point name
``` bash
$ glslangValidator -D -S frag -V test.frag -e main --target-env spirv1.0 -o frag.spv
test.frag
$ spirv-cross frag.spv --reflect
{
    "entryPoints" : [
        {
            "name" : "main",
            "mode" : "frag"
        }
    ],
    "inputs" : [
        {
            "type" : "vec3",
            "name" : "col",
            "location" : 0
        }
    ],
    "outputs" : [
        {
            "type" : "vec4",
            "name" : "@entryPointOutput",
            "location" : 0
        }
    ]
}
```

- glslangValidator without entry point name
``` bash
$ glslangValidator -D -S frag -V test.frag --target-env spirv1.0 -o frag.spv
test.frag
WARNING: Linking fragment stage: Entry point not found
$ spirv-cross frag.spv --reflect
{
    "entryPoints" : [
        {
            "name" : "",
            "mode" : "frag"
        }
    ]
}
```

- glslc without pass entry point name
``` bash
$ glslc -fshader-stage=frag -x hlsl --target-spv=spv1.0 test.frag -o frag.spv
$ spirv-cross frag.spv --reflect
{
    "entryPoints" : [
        {
            "name" : "main",
            "mode" : "frag"
        }
    ],
    "inputs" : [
        {
            "type" : "vec3",
            "name" : "col",
            "location" : 0
        }
    ],
    "outputs" : [
        {
            "type" : "vec4",
            "name" : "@entryPointOutput",
            "location" : 0
        }
    ]
}
```

ref: glslangValidator [Complete HLSL -> SPIR-V translator](https://github.com/KhronosGroup/glslang/issues/362)

I thought that if `glslc` don't need pass the entry point name and could auto detect entry name, it should be possible for `glslangValidator` to do the same thing without pass the entry point name. But now `glslangValidator` can't do this.

In haskell [spec](https://downloads.haskell.org/~ghc/8.8.4/docs/html/users_guide/glasgow_exts.html#template-haskell-quasi-quotation), quoter cannot be an arbitrary expression. It means syntax like `[frag "main"| ... |]` is impossible.
```
A quasi-quote has the form [quoter| string |].

    The ⟨quoter⟩ must be the name of an imported quoter, either qualified or unqualified; it cannot be an arbitrary expression.
```

Is there any advice for the design of `vert`, `frag` ... `mesh` in `Vulkan.Utils.ShaderQQ.HLSL.Glslang`? Or just remove `glslang` QuasiQuote support for `hlsl` and just provide `compileShaderQ`, `compileShader` with argument for passing entry point name in `Vulkan.Utils.ShaderQQ.HLSL.Glslang`?

**Comment by dpwiz** [comment]
A QuasiQuoter can generate a continuation that will accept more data and finish the generation.

**Comment by ukari** [comment]
squashed.

PS: now the usage for `vert` ... `mesh` in `Vulkan.Utils.ShaderQQ.HLSL.Glslang` has changed to syntax like the following example.
``` haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}

vertCode = $([vert|
  VSOutput main(const uint i : SV_VertexID)
      {
          VSOutput output;
          output.pos = float4(positions[i], 0, 1.0);
          output.col = colors[i];
          return output;
       }
  |] "main")
```

**Comment by expipiplus1** [comment]
I think to be honest I'd just leave it as hardcoded to `"main"` for the quasiquoter. The quasiquoters are intended to be a quick convenience and anything more involved (like multiple shaders in one file with different entrypoints) deserve to be files in their own right, or the user can fall back to `compileShaderQ`

**Comment by ukari** [comment]
squashed, please review it

**Comment by expipiplus1** [comment]
Looks good to me, thanks!

Happy to merge if the compile error is fixed. Could you also add some details to the changelog please? If you want this in a release sooner then feel free to bump the version of vulkan-utils!

**Comment by ukari** [comment]
actually I am not sure which version for `vulkan-utils` should be used for changelog

**Comment by expipiplus1** [comment]
Either in the WIP section or 0.5 if you want a release more quickly.

**Comment by ukari** [comment]
update & squashed, please review again

**Comment by expipiplus1** [comment]
Looks like a couple of the tests are failing because of changed line numbers. Is it possible to fix these please, then happy to merge?

**Comment by ukari** [comment]
Thanks for your review.

### the cause

I check some github ci log and found that this is caused by the lack of `shaderc`. I changed the some examples in `vulkan/examples` to make sure all shaderQQ modules could be checked to be compile successful which means all modules of `HLSL.Shaderc`, `HLSL.Glslang`, `GLSL.Shaderc`, `GLSL.Glslang` are used in `vulkan/examples`.

- the usage situation of all modules of `HLSL.Shaderc`, `HLSL.Glslang`, `GLSL.Shaderc`, `GLSL.Glslang` in `vulkan/examples`.
``` bash
$ grep -Ri "ShaderQQ" *
compute/Main.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang
hlsl/Pipeline.hs:import           Vulkan.Utils.ShaderQQ.HLSL.Glslang ( vert )
hlsl/Pipeline.hs:import           Vulkan.Utils.ShaderQQ.HLSL.Shaderc ( frag )
offscreen/Main.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang
rays/Pipeline.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang  ( glsl )
rays/Pipeline.hs:import qualified Vulkan.Utils.ShaderQQ.GLSL.Glslang as Glslang
rays/Pipeline.hs:import qualified Vulkan.Utils.ShaderQQ.GLSL.Shaderc as Shaderc
readme.md:- Convenient shader creation using the `Vulkan.Utils.ShaderQQ.comp` QuasiQuoter
resize/Pipeline.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang
resize/Julia.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang
sdl-triangle/Main.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Glslang ( frag )
sdl-triangle/Main.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Shaderc ( vert )

```

- the dependency on `shaderc/glslc` in `vulkan/examples`.
``` bash
$ grep -Ri "ShaderQQ.*.Shaderc" *
hlsl/Pipeline.hs:import           Vulkan.Utils.ShaderQQ.HLSL.Shaderc ( frag )
rays/Pipeline.hs:import qualified Vulkan.Utils.ShaderQQ.GLSL.Shaderc as Shaderc
sdl-triangle/Main.hs:import           Vulkan.Utils.ShaderQQ.GLSL.Shaderc ( vert )
```

For example, I import `GLSL.Glslang(frag)` and `GLSL.Shaderc(vert)` in `examples/sdl-triangle/Main.hs`. This cause the ci fails when compile the use of `vert` due to the dependency lack of `shaderc/glslc`.

### why some ci successfully build
In the current version of `expipiplus1/vulkan`, there is a `have-shaderc` flag to help skip the build of `examples/hlsl` to prevent the need of `shaderc/glslc`.

- the use of [`have-shaderc`](https://github.com/expipiplus1/vulkan/blob/4f163a3cc35d4fc5156e8bc6c33ab75ba7368c0d/.github/workflows/ci.yml#L128) in `ci.yml`
``` yaml
    - run: |
        if command -v glslc &> /dev/null; then
          cabal configure -fgeneric-instances -f-raytracing -fhave-shaderc
        else
          echo "glslc could not be found"
          cabal configure -fgeneric-instances -f-raytracing -f-have-shaderc
        fi
      shell: bash
```

- Some ci build passed successfully because of the build of `examples` is skipped due to their ghc version is `8.6.5`.
[`remove examples for ghc 8.6.5`](https://github.com/expipiplus1/vulkan/blob/4f163a3cc35d4fc5156e8bc6c33ab75ba7368c0d/.github/workflows/ci.yml#L108)
``` yaml
    - name: Remove examples for 8.6.5
      run: |
        sed -ibak '/examples/d' cabal.project
      if: matrix.ghc == '8.6.5'
```

- It seems only in the `Windows OS`, the `examples/hlsl`(which needs `shaderc/glslc`) is compiled. (I didn't check this exactly)

### the solution
#### the revert solution (which I choose)
- change `vulkan/examples` back to the current upstream version, so that only `examples/hlsl` needs `shaderc/glslc`.

#### the complex solution
- update `.github/workflows/ci.yml` to provide `shaderc/glslc` in ci environment
- update `examples/readme.md`

**Comment by ukari** [comment]
I didn't realize the existence of doctest before I run `stack test` just now.

now doctest failures has been fixed by changed the line number to the same as `doctest` expects.

**Comment by expipiplus1** [comment]
amazing, thanks

**Comment by expipiplus1** [comment]
released: https://hackage.haskell.org/package/vulkan-utils-0.5.0

thanks again.

**Pull request merged**
