### PR TITLE
Translate GLSL errors into TH fails

### PR DESCRIPTION
**Pull request by dpwiz**
Instead of crashing with "process exited with ExitCode 2" the error message in IDE hover contains relevant and actionable information:

```
• Exception when trying to run compile-time code:
    user error (/tmp/th-shader-32a8fe0ed8ce6695/shader.vert
ERROR: /home/dev/playground3/src/Render/Sprite/Shaders.hs:47: 'inPozition' : undeclared identifier 
ERROR: /home/dev/playground3/src/Render/Sprite/Shaders.hs:47: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
)
... remaining TH error ...
```

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks, this is way better. Would it be better to always output both stdout and stderr (I can't remember the output behaviour of glslangvalidator so this may not make senes.)?

**Comment by dpwiz** [comment]
I did a quick take and it was either exitSuccess and empty stderr or fail and empty stdout.

**Comment by expipiplus1** [comment]
Warnings can be generated on exitsuccess on stdout

```glsl
#define x=
```

produces:

```
test.vert
WARNING: 0:1: '#define' : missing space after macro name
```

Perhaps would be best to scan the output for the string `WARNING` and report that in TH with `reportWarning`.

**Comment by dpwiz** [comment]
Ah nice. Maybe the error case should be changed to `reportError` to remove more noise.

**Pull request merged**
