### PR TITLE
Windows cabal

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by expipiplus1** [comment]
Oh, it looks like it's using ghc 8.10.2 for all builds?!

**Comment by expipiplus1** [comment]
I'm actually an idiot, even commented on the thread... https://github.com/actions/setup-haskell/issues/21

**Comment by expipiplus1** [comment]
@dpwiz If you have a moment would it be possible for you to sanity check the new Cabal/Windows instructions, please? No hurry or pressure!

**Comment by dpwiz** [comment]
Looks doable. Maybe add a `split-sections: true` recommendation?

I want to try it out sometime for real, will keep on my notifications todo for now.

**Comment by expipiplus1** [comment]
good idea, I'll do that next time I reboot to windows.

Should probably be a section in the readme regarding packaging binaries for distribution.

**Pull request merged**
