### PR TITLE
Use language-c on hackage

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by expipiplus1** [comment]
@lancelet Any idea why this could be failing on OSX: https://github.com/expipiplus1/vulkan/pull/159/checks?check_run_id=1081750725?

**Comment by lancelet** [comment]
@expipiplus1 Hmm... I'm not sure. That CI error isn't very helpful. I'll probably have to poke around locally, but it's unlikely that I'll have time before this weekend at the earliest.

Does it fail repeatably? (ie. not just a spurious failure on just one run)

**Comment by expipiplus1** [comment]
> @expipiplus1 Hmm... I'm not sure. That CI error isn't very helpful. I'll probably have to poke around locally, but it's unlikely that I'll have time before this weekend at the earliest.

Sure, no hurry at all. I'll merge this as I can't see how it's related.

> Does it fail repeatably? (ie. not just a spurious failure on just one run)

Yeah, it's failed quite a lot on this branch. It didn't happen on a branch which didn't touch any haskell code (in which case I assume stack was pulling from the cache). I'll update if it breaks elsewhere

**Comment by expipiplus1** [comment]
Seems to be fixed, :shrug:

**Comment by expipiplus1** [comment]
nope :/ https://github.com/expipiplus1/vulkan/runs/1100327600?check_suite_focus=true

**Pull request merged**
